[package]
name = "config-parser-common"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = { version = "2.0.94", features = ["full", "extra-traits"] }
