[package]
name = "derive_config_parser"
version = "0.1.0"
autotests = false
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0.38"
syn = { version = "2.0.92", features = ["extra-traits"] }

